### ISSUE TITLE
:SYS:CLK:BYPASS knob has bad side effects

### ISSUE THREAD

**Issue by zack-vii** [D-TACQ/ACQ400RELEASE#1]
Somewhere between release 130 and 227 disabling bypass got a bad side effect that often breaks clock propagation if external clock is used. 
```
SYS:CLK:PMUX   FPCLK
SIG:SRC:CLK:0  0
SIG:SRC:CLK:1  0
SIG:CLK_MB:FIN 10000000
SIG:CLK_MB:SET 50000000
SYS:CLK:BYPASS 0
```
current behavior:
 SYS:CLK:CONFIG gets stuck in "33M333-80M"  (even if PLAN is set to e.g. 50M) and SYS:CLK:LOL is lit.
expected behavior:
 SYS:CLK:CONFIG should show "-1.00e+07--5.00e+07" and the clock should propagate correctly.

**Comment by petermilne** [comment]
Please remote BYPASS BEFORE SET. This works:
SYS:CLK:FPMUX   FPCLK
SIG:CLK_MB:FIN 10000000
SYS:CLK:BYPASS 0
SIG:CLK_MB:SET 50000000
